import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import { TopNav } from "./_components/topNav";

export const metadata = {
  title: "T3 Gallery",
  description: "Generated by loyal subscriber theo youtube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${GeistSans.variable} flex flex-col gap-4 font-sans`}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
